#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GettingStartedTutorial.Resource", IsApplication=true)]

namespace GettingStartedTutorial
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int activity_horizontal_margin = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int activity_vertical_margin = 2130771969;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int DataViewTitle = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int DataViewTxt = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int MyButton = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int scrollView2 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int statusView = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int statusViewTitle = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int statusViewTxt = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int textView = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int textViewStatus = 2130903048;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050002
			public const int dataView_text = 2131034114;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7F050003
			public const int statusView_text = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
